### ISSUE TITLE
main: silent extension activation failure

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#435]
- Extension fails to start but no error is showed to the user.
- Document language appears to be `Ansible` and syntax highlighting works, only adding more to the confusion
- There is no Ansible output channel, indication of crash
- Extensio host output channel contains the unpleasant details:

```
[2022-03-02 09:54:39.821] [exthost] [error] Activating extension redhat.ansible failed due to an error:
[2022-03-02 09:54:39.822] [exthost] [error] Error: Cannot find module './features/vault'
Require stack:
- c:\Users\sorin\.vscode\extensions\redhat.ansible-0.7.1\out\client\src\extension.js
- c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:32271)
    at Function.p._load (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:28855)
    at Function.v._load (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:107:60382)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Users\sorin\.vscode\extensions\redhat.ansible-0.7.1\out\client\src\extension.js:26:17)
    at Module.u._compile (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:32271)
    at Function.p._load (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:28855)
    at Function.v._load (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:107:60382)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
    at w._loadCommonJSModule (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:30425)
    at w._doActivateExtension (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:13341)
    at w._activateExtension (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:12293)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at w.$activate (c:\Users\sorin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:21810)
```

Update: apparently vsix archive contains only extension.js file and missing the other nearby js files.

Not sure when this happened but it does highlight a fatal flaws in our testing.

**Comment by aussielunix** [comment]
I am hitting this now with v0.11.10 and a fresh vscode install on Fedora 36 (Gnome)
Only extensions I have installed are 

![image](https://user-images.githubusercontent.com/261833/180906763-d516846a-bd7a-4224-b909-6f8161027c54.png)

Extension fails to activate
Downgrading to v0.10.0 and it activates again

```
[2022-07-26 11:53:48.839] [exthost] [error] Activating extension redhat.ansible failed due to an error:
[2022-07-26 11:53:48.839] [exthost] [error] Error: Cannot find module './features/vault'
Require stack:
- /home/lunix/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
    at Function.v._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
    at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (/usr/share/code/resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/home/lunix/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js:30:17)
    at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
    at Function.v._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
    at Function.b._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at w._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:30173)
    at w._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14758)
    at w._activateExtension (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13706)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at b._activate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
    at b._waitForDepsThenActivate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
    at b._initialize (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

**Comment by ianburrowes** [comment]
Also stumbled onto this issue with v0.11.10, on Win11 / WSL2 after wondering why my Ansible syntax highlighting had suddenly stopped working.  Downgrading to the previous v0.10.0 got it working again.

**Comment by jlucktay** [comment]
I have a similar error on macOS 12.4, VSCode 1.69.2, and Ansible extension 0.11.10:

```log
[2022-07-26 08:57:18.717] [exthost] [error] Activating extension redhat.ansible failed due to an error:
[2022-07-26 08:57:18.717] [exthost] [error] Error: Cannot find module './features/vault'
Require stack:
- /Users/jameslucktaylor/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
	at Module._load (node:internal/modules/cjs/loader:832:27)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/jameslucktaylor/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js:30:17)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:30173)
	at w._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14758)
	at w._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13706)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async b._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async b._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async b._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

The `Runtime Status` tab shows `Not yet activated`:

![image](https://user-images.githubusercontent.com/460028/180955895-c7298c4a-f5fa-48e2-81d5-cf13ae8fbd11.png)

**Comment by ssbarnea** [comment]
Please install `0.11.11`, i fixed the bad release. Now I also working on introducing some preventive measures for avoiding the same accident from happening again. That is the 2nd time it happens, the first time was more than an year ago.

**Comment by df-cgdm** [comment]
+1
