### ISSUE TITLE
spawn C:\windows\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by craph** [ansible/vscode-ansible#465]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

When I start vscode on workspaces containing Ansible code I have this popup : 
![image](https://user-images.githubusercontent.com/14820052/160093998-dbe3b480-e6f7-4f85-a4a7-5ebdc2ab90dd.png)

### Extension version

v0.8.1

### VS Code version

1.65.2

### Ansible Version

```shell
Ansible not installed. Only the extension in vscode is installed.
```

### OS / Environment

Windows 10 : Windows_NT x64 10.0.19042

**Comment by craph** [comment]
I got this error when I switch from Yaml to Ansible file language (but not on each files...)
![image](https://user-images.githubusercontent.com/14820052/160583285-4f5d56e7-c6c3-415f-bd91-db6c75628337.png)
![image](https://user-images.githubusercontent.com/14820052/160583389-25df6e05-1556-487f-8e88-44081d3e0e48.png)

**Comment by craph** [comment]
In the `Output` for `Ansible Server` I have this if can help : 
```
Error: spawn C:\windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\windows\\system32\\cmd.exe',
  path: 'C:\\windows\\system32\\cmd.exe',
  spawnargs: [ '/d', '/s', '/c', '"which ansible-lint"' ],
  cmd: 'which ansible-lint',
  stdout: '',
  stderr: ''
}
Error: spawn C:\windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\windows\\system32\\cmd.exe',
  path: 'C:\\windows\\system32\\cmd.exe',
  spawnargs: [ '/d', '/s', '/c', '"whereis ansible-lint"' ],
  cmd: 'whereis ansible-lint',
  stdout: '',
  stderr: ''
}
Path for lint:  undefined
Validating using ansible syntax-check
not a playbook...
```

**Comment by craph** [comment]
> @craph The extension does not work on native windows if the language of file is identified as `Ansible` [bottom right of VSCode](https://github.com/ansible/vscode-ansible#activating-red-hat-ansible-extension) as it runs `ansible` commands to gather plugins docs and ansible configuration, which requires `ansible` to be installed on the system running VSCode. Refer https://github.com/ansible/vscode-ansible#requirements
> 
> You can enable WSL2 on windows for the extension to work.
> 
> I have raised an issue #467 to notify users about incompatible OS.

Hello @ganeshrn ,

Thank you very much for the update.
But can you explain how to configure it with WSL2 ?

I have WSL2 enable on my windows machine but I don't know how to have this working with vscode and with your extension Ansible.

**Comment by ganeshrn** [comment]
@craph You can refer this blog https://matthew-d-clark.medium.com/wsl2-setup-for-distributing-to-iac-developers-ansible-focus-520883c83b02

**Comment by somepad** [comment]
May I jump in here?
I actually do have ansible and ansible-lint in my Windows box, but event after setting up `ansible.ansibleLint.path` property extension still tries to run something like `which C:\\Users\\USERNAME\\AppData\\Roaming\\Python\\Python39\\Scripts\\ansible-lint.exe`. I wonder why it tries lookup anything when it already have the correct path...
