### ISSUE TITLE
Completions appear to have stopped working in v0.11.11

### ISSUE THREAD

**Issue by WoodyWoodsta** [ansible/vscode-ansible#571]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

After having an issue with v0.11.10 described [here](https://github.com/ansible/vscode-ansible/issues/435), I upgraded to v0.11.11, which appears to have broken completions.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/8268040/181192503-bd52087b-f57c-4aad-a0fd-3af66b00d9ef.png">

Log output from the Ansible Server shown below.

### Extension version

v0.11.11

### VS Code version

v1.69.2

### Ansible Version

```shell
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/woodywoodsta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/woodywoodsta/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

MacOS 12.5

### Relevant log output

```shell
[Error - 08:48:41] An error occurred in 'onCompletion' handler: [TypeError] Cannot read properties of undefined (reading 'provideRedirectModules')
TypeError: Cannot read properties of undefined (reading 'provideRedirectModules')
    at /Users/woodywoodsta/.vscode/extensions/redhat.ansible-0.11.11/out/server/src/server.js:2:31260
    at Generator.next (<anonymous>)
    at s (/Users/woodywoodsta/.vscode/extensions/redhat.ansible-0.11.11/out/server/src/server.js:2:29606)
```

**Comment by lxwulf** [comment]
I can confirm this, I have the same problem even with a slight newer Ansible version.

**Short Info:**

OS: Fedora 36
Ansible Version:
```shell
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/home/ok/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ok/Downloads/pyapps/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ok/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ok/Downloads/pyapps/bin/ansible
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.1.2
  libyaml = True
```
VSCodium Version:
```Shell
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-19T00:58:08.152Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.18.13-200.fc36.x86_64
```

**Comment by AmeBoond** [comment]
Same bug here, no completion nether lint. 
It's OK in version 0.10.0

**Comment by jeinwag** [comment]
Also experiencing several issues with v0.11.11, looks like the extensions can't activate properly:
```
[2022-07-27 15:08:48.254] [exthost] [error] Activating extension redhat.ansible failed due to an error:
[2022-07-27 15:08:48.254] [exthost] [error] Error: Cannot find module './features/vault'
Require stack:
- /Users/*****/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
	at Module._load (node:internal/modules/cjs/loader:832:27)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/*****/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js:30:17)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:30173)
	at w._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14758)
	at w._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13706)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async b._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async b._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async b._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)```

**Comment by jeinwag** [comment]
Looks like most of the code is missing from the current release, at least by comparing file sizes:
```
vscode@9bb2dab48b1f:redhat.ansible-0.10.0/ $ ls -lh **/*.js               
-rw-r--r-- 1 vscode vscode 271K Jul 27 12:23 out/client/src/extension.js
-rw-r--r-- 1 vscode vscode 432K Jul 27 12:23 out/server/src/server.js
vscode@9bb2dab48b1f:redhat.ansible-0.10.0/ $ cd -                         
~/.vscode-server/extensions/redhat.ansible-0.11.10
vscode@9bb2dab48b1f:redhat.ansible-0.11.10/ $ ls -lh **/*.js              
-rw-r--r-- 1 vscode vscode 3.9K Jul 27 11:10 out/client/src/extension.js
-rw-r--r-- 1 vscode vscode 2.0K Jul 27 11:10 out/server/src/server.js
```

**Comment by ganeshrn** [comment]
Thanks for raising the issue. There has been a major refactor on how we build/release the extension and ansible-language-server recently and this issue seems like a fallout of that. Sorry for the inconvenience, please bear with us as we iron out the issues.

**Comment by priyamsahoo** [comment]
Please update the extension to v0.11.12 (pre-release).
It should work now :)

**Comment by lxwulf** [comment]
> Please update the extension to v0.11.12 (pre-release).
> It should work now :)

Can confirm this! Thanks for the fast fixing! ✌️

**Comment by WoodyWoodsta** [comment]
Working for me, thank you!
