### ISSUE TITLE
Extenstion v0.11.10 fails to load

### ISSUE THREAD

**Issue by antonc42** [ansible/vscode-ansible#578]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

When updated to v0.11.10, the extension doesn't start. Downgrading to v0.10.0 makes everything work again. See VSCode extension log below. 

### Extension version

v0.11.10

### VS Code version

1.69.2

### Ansible Version

```shell
ansible [core 2.13.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/my-collection/.venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/my-collection/.venv/bin/ansible
  python version = 3.10.5 (main, Jun 11 2022, 16:53:24) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = False
```

### OS / Environment

Ubuntu 20.04

```
ansible-lint --version
ansible-lint 6.3.0 using ansible 2.13.1
```

VSCode version (snap):
```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:14:10.636Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.14.0-1045-oem snap
```

### Relevant log output

```shell
[2022-07-29 10:42:28.971] [exthost] [info] Extension host with pid 2004397 started
[2022-07-29 10:42:28.971] [exthost] [info] Skipping acquiring lock for /home/user/.config/Code/User/workspaceStorage/b0961df62a740643bd4f8c413afc29b4.
[2022-07-29 10:42:29.126] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:ansible', root cause: redhat.ansible
[2022-07-29 10:42:29.200] [exthost] [info] ExtensionService#_doActivateExtension redhat.vscode-yaml, startup: false, activationEvent: 'onLanguage:ansible', root cause: redhat.ansible
[2022-07-29 10:42:29.225] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-07-29 10:42:29.243] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-07-29 10:42:29.244] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2022-07-29 10:42:29.246] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-07-29 10:42:29.397] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-07-29 10:42:29.416] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-07-29 10:42:29.496] [exthost] [info] ExtensionService#_doActivateExtension redhat.ansible, startup: false, activationEvent: 'onLanguage:ansible'
[2022-07-29 10:42:29.500] [exthost] [error] Activating extension redhat.ansible failed due to an error:
[2022-07-29 10:42:29.500] [exthost] [error] Error: Cannot find module './features/vault'
Require stack:
- /home/user/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js
- /snap/code/102/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/102/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/102/usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
	at Module._load (node:internal/modules/cjs/loader:832:27)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/snap/code/102/usr/share/code/resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/home/user/.vscode/extensions/redhat.ansible-0.11.10/out/client/src/extension.js:30:17)
	at Module.u._compile (/snap/code/102/usr/share/code/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.i._load (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32133)
	at Function.v._load (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:28715)
	at Function.b._load (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61601)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/snap/code/102/usr/share/code/resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:30173)
	at w._doActivateExtension (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14758)
	at w._activateExtension (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13706)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async b._activate (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async b._waitForDepsThenActivate (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async b._initialize (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
```

**Comment by geoffreyvanwyk** [comment]
Upgrading to the prelease version 0.11.12 works.

**Comment by tmailloux-desjardins** [comment]
I did upgrade to 0.11.12 the extension was not loading. Downgrading to v0.10.0 solve it for me.
Unfortunately I can't provide more information/log why it was not working

**Comment by antonc42** [comment]
Switching to pre-release v0.11.12 works for me too. Is there an estimate for when this will become the regular release version?
